// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-yISSx0-4lc0nVp6DosRxtlKTp5xTVeE',
    appId: '1:1098117801309:web:1704945234735db61034b4',
    messagingSenderId: '1098117801309',
    projectId: 'rebuy-3702d',
    authDomain: 'rebuy-3702d.firebaseapp.com',
    storageBucket: 'rebuy-3702d.appspot.com',
    measurementId: 'G-NNLRN601SD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfGi3G1XXPan1zoZIP3UrYX1v01zlXvT4',
    appId: '1:1098117801309:android:0776255450cc65ff1034b4',
    messagingSenderId: '1098117801309',
    projectId: 'rebuy-3702d',
    storageBucket: 'rebuy-3702d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtN5K50LlrEgOwCgO1sIwAF6e0HQfOp98',
    appId: '1:1098117801309:ios:b402912fa1001ce01034b4',
    messagingSenderId: '1098117801309',
    projectId: 'rebuy-3702d',
    storageBucket: 'rebuy-3702d.appspot.com',
    androidClientId: '1098117801309-a1hn047ud7urlh1hiobg0d0vjjm99n07.apps.googleusercontent.com',
    iosClientId: '1098117801309-qj513l86ocjquvrkqab5u95t2n0spvc7.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminRebuyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtN5K50LlrEgOwCgO1sIwAF6e0HQfOp98',
    appId: '1:1098117801309:ios:3656aa7593bc70571034b4',
    messagingSenderId: '1098117801309',
    projectId: 'rebuy-3702d',
    storageBucket: 'rebuy-3702d.appspot.com',
    androidClientId: '1098117801309-a1hn047ud7urlh1hiobg0d0vjjm99n07.apps.googleusercontent.com',
    iosClientId: '1098117801309-p7b5buq33cpotar5tnvlegbfnkpj2jpe.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminRebuyApp.RunnerTests',
  );
}
