// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh491GvAX3hpeq-An4bbQC7wTTe2Dz82g',
    appId: '1:430553251505:web:834c4e151ae55fceee6c90',
    messagingSenderId: '430553251505',
    projectId: 'rebuy-ef5a9',
    authDomain: 'rebuy-ef5a9.firebaseapp.com',
    storageBucket: 'rebuy-ef5a9.appspot.com',
    measurementId: 'G-N7NTSY81JD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg2SWktzTSdXwT--5kKFA91dTJ__P1CHk',
    appId: '1:430553251505:android:954a3e838fb6d1c9ee6c90',
    messagingSenderId: '430553251505',
    projectId: 'rebuy-ef5a9',
    storageBucket: 'rebuy-ef5a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbottmyJWPCMufxOU8do4A-KsbZq-IyUA',
    appId: '1:430553251505:ios:bf50b761dfec1833ee6c90',
    messagingSenderId: '430553251505',
    projectId: 'rebuy-ef5a9',
    storageBucket: 'rebuy-ef5a9.appspot.com',
    iosBundleId: 'com.example.adminRebuyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbottmyJWPCMufxOU8do4A-KsbZq-IyUA',
    appId: '1:430553251505:ios:987803fa575e57f3ee6c90',
    messagingSenderId: '430553251505',
    projectId: 'rebuy-ef5a9',
    storageBucket: 'rebuy-ef5a9.appspot.com',
    iosBundleId: 'com.example.adminRebuyApp.RunnerTests',
  );
}
